import Foundation

// Curated worldwide destination guide: where, what big animals, and when.
// Season windows are the commonly cited best months — always re-verify with
// operators before booking (El Niño years shift things).

struct BigThing: Identifiable {
    let id: String
    let emoji: String
    let zh: String
    let en: String

    var name: String { loc(zh, en) }
}

struct Destination: Identifiable {
    let id: String          // stable key (en name)
    let zh: String
    let en: String
    let regionZH: String
    let regionEN: String
    let lat: Double
    let lon: Double
    let months: Set<Int>    // best months, 1-12
    let tempC: ClosedRange<Int>
    let species: [String]   // BigThing ids
    let noteZH: String
    let noteEN: String
    let coldWater: Bool

    var name: String { loc(zh, en) }
    var region: String { loc(regionZH, regionEN) }
    var note: String { loc(noteZH, noteEN) }
}

enum DestinationGuide {
    static let things: [BigThing] = [
        BigThing(id: "whaleshark", emoji: "🐋", zh: "鲸鲨", en: "Whale shark"),
        BigThing(id: "manta", emoji: "🛸", zh: "蝠鲼", en: "Manta"),
        BigThing(id: "hammerhead", emoji: "🔨", zh: "锤头鲨群", en: "Hammerheads"),
        BigThing(id: "orca", emoji: "🐳", zh: "虎鲸", en: "Orca"),
        BigThing(id: "humpback", emoji: "🎶", zh: "座头鲸", en: "Humpback"),
        BigThing(id: "tigershark", emoji: "🐅", zh: "虎鲨", en: "Tiger shark"),
        BigThing(id: "thresher", emoji: "🦊", zh: "长尾鲨", en: "Thresher"),
        BigThing(id: "reefshark", emoji: "🦈", zh: "鲨鱼墙/礁鲨", en: "Shark walls"),
        BigThing(id: "sealion", emoji: "🦭", zh: "海狮/海狗", en: "Sea lions"),
        BigThing(id: "mola", emoji: "🥏", zh: "翻车鱼", en: "Mola mola"),
        BigThing(id: "cuttlefish", emoji: "🦑", zh: "巨型乌贼", en: "Giant cuttlefish"),
        BigThing(id: "sardine", emoji: "🌪", zh: "沙丁鱼风暴", en: "Sardine run"),
        BigThing(id: "gpo", emoji: "🐙", zh: "GPO/狼鳗", en: "GPO & wolf eels"),
        BigThing(id: "macro", emoji: "🔬", zh: "微距天堂", en: "Macro heaven"),
        BigThing(id: "wreck", emoji: "🚢", zh: "沉船", en: "Wrecks"),
        BigThing(id: "cave", emoji: "🕳", zh: "洞穴/洞潜", en: "Caves & caverns"),
        BigThing(id: "croc", emoji: "🐊", zh: "美洲鳄", en: "Crocodiles"),
        BigThing(id: "mobula", emoji: "🪁", zh: "魔鬼鱼风暴", en: "Mobula storm"),
        BigThing(id: "dragon", emoji: "🐉", zh: "叶海龙", en: "Sea dragons"),
        BigThing(id: "kelp", emoji: "🌿", zh: "巨藻森林", en: "Kelp forest"),
    ]

    static func thing(_ id: String) -> BigThing? {
        things.first { $0.id == id }
    }

    // helper: month set from inclusive spans (wraps across new year)
    private static func m(_ spans: [(Int, Int)]) -> Set<Int> {
        var out = Set<Int>()
        for (a, b) in spans {
            var x = a
            while true {
                out.insert(x)
                if x == b { break }
                x = x % 12 + 1
            }
        }
        return out
    }

    static let all: [Destination] = [
        // ===== 珊瑚三角 & 东南亚 =====
        Destination(id: "Raja Ampat", zh: "四王群岛", en: "Raja Ampat",
            regionZH: "印尼", regionEN: "Indonesia", lat: -0.5, lon: 130.5,
            months: m([(10, 4)]), tempC: 27...30,
            species: ["manta", "reefshark", "macro"],
            noteZH: "地球生物多样性之王，蝠鲼清洁站 + 须鲨，船宿为主",
            noteEN: "Peak marine biodiversity on Earth; manta stations, wobbegongs; liveaboard",
            coldWater: false),
        Destination(id: "Komodo", zh: "科莫多", en: "Komodo",
            regionZH: "印尼", regionEN: "Indonesia", lat: -8.55, lon: 119.5,
            months: m([(4, 11)]), tempC: 24...28,
            species: ["manta", "reefshark", "macro"],
            noteZH: "强流喂出来的生态，Manta Point 排队洗澡，流潜技术要求高",
            noteEN: "Current-fed reefs, manta trains; strong-current skills required",
            coldWater: false),
        Destination(id: "Sipadan", zh: "诗巴丹", en: "Sipadan",
            regionZH: "马来西亚", regionEN: "Malaysia", lat: 4.11, lon: 118.63,
            months: m([(4, 12)]), tempC: 27...30,
            species: ["reefshark"],
            noteZH: "杰克风暴 + 梭鱼龙卷风 + 满墙海龟，每日限额需提前订",
            noteEN: "Jack & barracuda tornadoes, turtles everywhere; daily permits",
            coldWater: false),
        Destination(id: "Richelieu Rock", zh: "斯米兰/黎塞留礁", en: "Similan / Richelieu",
            regionZH: "泰国", regionEN: "Thailand", lat: 9.36, lon: 98.02,
            months: m([(11, 4)]), tempC: 27...29,
            species: ["whaleshark", "manta", "macro"],
            noteZH: "国家公园每年 10 月中-5 月中开放，2-4 月鲸鲨季",
            noteEN: "Park open mid-Oct–mid-May; whale sharks Feb–Apr",
            coldWater: false),
        Destination(id: "Malapascua", zh: "妈妈拍丝瓜", en: "Malapascua",
            regionZH: "菲律宾", regionEN: "Philippines", lat: 11.33, lon: 124.12,
            months: m([(1, 12)]), tempC: 26...30,
            species: ["thresher"],
            noteZH: "全球唯一稳定看长尾鲨的地方，清晨下水，全年可见",
            noteEN: "The only reliable thresher spot on Earth; dawn dives, year-round",
            coldWater: false),
        Destination(id: "Anilao", zh: "阿尼洛", en: "Anilao",
            regionZH: "菲律宾", regionEN: "Philippines", lat: 13.75, lon: 120.9,
            months: m([(11, 5)]), tempC: 26...29,
            species: ["macro"],
            noteZH: "微距摄影师的朝圣地，海蛞蝓密度爆表",
            noteEN: "Macro photographer pilgrimage; nudibranch density off the charts",
            coldWater: false),
        Destination(id: "Lembeh", zh: "蓝碧海峡", en: "Lembeh Strait",
            regionZH: "印尼", regionEN: "Indonesia", lat: 1.45, lon: 125.23,
            months: m([(7, 10)]), tempC: 26...29,
            species: ["macro"],
            noteZH: "黑沙 muck diving 之王：拟态章鱼、毛毛鱼、火焰乌贼",
            noteEN: "Muck diving capital: mimic octopus, hairy frogfish, flamboyant cuttlefish",
            coldWater: false),
        Destination(id: "Moalboal", zh: "墨宝", en: "Moalboal",
            regionZH: "菲律宾", regionEN: "Philippines", lat: 9.94, lon: 123.37,
            months: m([(1, 12)]), tempC: 26...30,
            species: ["sardine"],
            noteZH: "岸边就是常驻沙丁鱼球，自由潜水员和你抢位置",
            noteEN: "Resident sardine ball right off the beach, year-round",
            coldWater: false),
        Destination(id: "Nusa Penida", zh: "佩尼达岛", en: "Nusa Penida",
            regionZH: "印尼巴厘", regionEN: "Bali, Indonesia", lat: -8.73, lon: 115.54,
            months: m([(7, 10)]), tempC: 20...27,
            species: ["mola", "manta"],
            noteZH: "7-10 月冷涌带来翻车鱼，Manta Point 全年，水温骤变带电脑看",
            noteEN: "Mola season Jul–Oct on cold upwellings; mantas year-round",
            coldWater: false),
        Destination(id: "Tubbataha", zh: "图巴塔哈", en: "Tubbataha",
            regionZH: "菲律宾", regionEN: "Philippines", lat: 8.85, lon: 119.92,
            months: m([(3, 6)]), tempC: 27...30,
            species: ["reefshark", "whaleshark", "manta"],
            noteZH: "苏禄海孤礁，只有 3-6 月船宿季能去，原始度顶级",
            noteEN: "Remote Sulu Sea atolls; liveaboard season Mar–Jun only",
            coldWater: false),

        // ===== 太平洋岛屿 =====
        Destination(id: "Palau", zh: "帕劳", en: "Palau",
            regionZH: "密克罗尼西亚", regionEN: "Micronesia", lat: 7.27, lon: 134.38,
            months: m([(11, 4)]), tempC: 28...30,
            species: ["reefshark", "manta", "wreck"],
            noteZH: "蓝角放流 + 德国水道蝠鲼 + 水母湖，流钩必备",
            noteEN: "Blue Corner drift, German Channel mantas, Jellyfish Lake; reef hooks",
            coldWater: false),
        Destination(id: "Yap", zh: "雅浦", en: "Yap",
            regionZH: "密克罗尼西亚", regionEN: "Micronesia", lat: 9.53, lon: 138.12,
            months: m([(12, 4)]), tempC: 28...30,
            species: ["manta"],
            noteZH: "蝠鲼求偶季 12-4 月，清洁站近距离稳定观察",
            noteEN: "Manta mating season Dec–Apr; reliable cleaning stations",
            coldWater: false),
        Destination(id: "Chuuk Lagoon", zh: "楚克泻湖", en: "Chuuk (Truk) Lagoon",
            regionZH: "密克罗尼西亚", regionEN: "Micronesia", lat: 7.42, lon: 151.78,
            months: m([(12, 4)]), tempC: 28...30,
            species: ["wreck"],
            noteZH: "二战日本舰队沉船 60+ 艘，沉船潜水的世界之最，Tech 深度更精彩",
            noteEN: "60+ WWII Japanese wrecks — the world's wreck mecca; tech depths shine",
            coldWater: false),
        Destination(id: "Fakarava", zh: "法卡拉瓦", en: "Fakarava",
            regionZH: "法属波利尼西亚", regionEN: "French Polynesia", lat: -16.3, lon: -145.6,
            months: m([(6, 7), (1, 12)]), tempC: 26...29,
            species: ["reefshark"],
            noteZH: "南口鲨鱼墙数百条灰礁鲨；6-7 月满月石斑产卵季是自然奇观",
            noteEN: "Wall of hundreds of grey reef sharks; Jun–Jul grouper spawning is epic",
            coldWater: false),
        Destination(id: "Tonga", zh: "汤加", en: "Tonga",
            regionZH: "南太平洋", regionEN: "South Pacific", lat: -18.65, lon: -173.98,
            months: m([(7, 10)]), tempC: 23...26,
            species: ["humpback"],
            noteZH: "全球少数可下水与座头鲸母子同游的地方（浮潜）",
            noteEN: "One of few places to swim with humpback mums & calves (snorkel)",
            coldWater: false),

        // ===== 东太平洋大物三角 =====
        Destination(id: "Galapagos", zh: "加拉帕戈斯", en: "Galápagos",
            regionZH: "厄瓜多尔", regionEN: "Ecuador", lat: -0.4, lon: -91.5,
            months: m([(6, 11)]), tempC: 16...24,
            species: ["whaleshark", "hammerhead", "sealion", "mola"],
            noteZH: "Darwin/Wolf 的怀孕鲸鲨 6-11 月，锤头鲨全年，海鬣蜥彩蛋",
            noteEN: "Pregnant whale sharks at Darwin Jun–Nov, hammerheads year-round",
            coldWater: true),
        Destination(id: "Cocos Island", zh: "科科斯岛", en: "Cocos Island",
            regionZH: "哥斯达黎加", regionEN: "Costa Rica", lat: 5.53, lon: -87.07,
            months: m([(6, 11)]), tempC: 24...28,
            species: ["hammerhead", "tigershark", "whaleshark"],
            noteZH: "36 小时航渡换来的锤头鲨风暴，雨季（6-11）鲨最多",
            noteEN: "36-hour crossing to hammerhead storms; wet season = more sharks",
            coldWater: false),
        Destination(id: "Socorro", zh: "索科罗", en: "Socorro (Revillagigedo)",
            regionZH: "墨西哥", regionEN: "Mexico", lat: 18.78, lon: -110.97,
            months: m([(11, 5)]), tempC: 21...26,
            species: ["manta", "humpback", "hammerhead", "tigershark"],
            noteZH: "巨型蝠鲼主动找潜水员互动；1-3 月加上座头鲸伴唱",
            noteEN: "Giant mantas seek out divers; humpbacks singing Jan–Mar",
            coldWater: false),
        Destination(id: "La Paz", zh: "拉巴斯", en: "La Paz / Sea of Cortez",
            regionZH: "墨西哥", regionEN: "Mexico", lat: 24.16, lon: -110.32,
            months: m([(8, 11)]), tempC: 24...29,
            species: ["sealion", "whaleshark", "mobula"],
            noteZH: "海狮幼崽扑脸 + 秋冬鲸鲨；春季魔鬼鱼风暴在外海",
            noteEN: "Sea lion pups in your face; whale sharks in fall; mobula storms",
            coldWater: false),

        // ===== 大西洋 & 加勒比 =====
        Destination(id: "Tiger Beach", zh: "虎鲨滩", en: "Tiger Beach",
            regionZH: "巴哈马", regionEN: "Bahamas", lat: 26.86, lon: -79.05,
            months: m([(10, 1)]), tempC: 24...28,
            species: ["tigershark", "reefshark"],
            noteZH: "清水白沙上与虎鲨平静共处，鲨鱼潜标杆",
            noteEN: "Calm tiger sharks over white sand — the benchmark shark dive",
            coldWater: false),
        Destination(id: "Bimini", zh: "比米尼", en: "Bimini",
            regionZH: "巴哈马", regionEN: "Bahamas", lat: 25.73, lon: -79.3,
            months: m([(12, 3)]), tempC: 23...26,
            species: ["hammerhead"],
            noteZH: "大锤头鲨冬季聚集，浅水近距离",
            noteEN: "Great hammerheads gather in winter, shallow & close",
            coldWater: false),
        Destination(id: "Banco Chinchorro", zh: "钦乔罗礁", en: "Banco Chinchorro",
            regionZH: "墨西哥", regionEN: "Mexico", lat: 18.59, lon: -87.33,
            months: m([(5, 9)]), tempC: 27...29,
            species: ["croc"],
            noteZH: "红树林清水里与美洲鳄面对面（浮潜笼外）",
            noteEN: "Face-to-face with American crocs in clear mangrove water",
            coldWater: false),
        Destination(id: "Isla Mujeres", zh: "女人岛", en: "Isla Mujeres",
            regionZH: "墨西哥", regionEN: "Mexico", lat: 21.23, lon: -86.73,
            months: m([(6, 9)]), tempC: 27...29,
            species: ["whaleshark", "manta"],
            noteZH: "夏季数百条鲸鲨聚集海面滤食（浮潜），全球最大聚集",
            noteEN: "Hundreds of whale sharks feeding at the surface — largest aggregation",
            coldWater: false),
        Destination(id: "Cenotes", zh: "尤卡坦天坑", en: "Yucatán Cenotes",
            regionZH: "墨西哥", regionEN: "Mexico", lat: 20.35, lon: -87.34,
            months: m([(1, 12)]), tempC: 24...25,
            species: ["cave"],
            noteZH: "水下钟乳石宫殿 + 光柱，你的洞穴训练路线终点站",
            noteEN: "Stalactite palaces and light beams — where cave training leads",
            coldWater: false),
        Destination(id: "Azores", zh: "亚速尔群岛", en: "Azores",
            regionZH: "葡萄牙", regionEN: "Portugal", lat: 38.53, lon: -28.63,
            months: m([(7, 10)]), tempC: 18...23,
            species: ["mobula", "whaleshark", "reefshark"],
            noteZH: "大西洋海山：Princess Alice 的魔鬼鱼群 + 蓝鲨潜",
            noteEN: "Atlantic seamounts: mobula squadrons at Princess Alice, blue sharks",
            coldWater: true),

        // ===== 红海 & 印度洋 =====
        Destination(id: "Red Sea North", zh: "北红海", en: "Red Sea North",
            regionZH: "埃及", regionEN: "Egypt", lat: 27.3, lon: 33.8,
            months: m([(3, 5), (9, 11)]), tempC: 22...28,
            species: ["wreck", "reefshark"],
            noteZH: "Thistlegorm 沉船 + Ras Mohammed 鱼墙，性价比之王",
            noteEN: "SS Thistlegorm + Ras Mohammed fish walls; best value liveaboards",
            coldWater: false),
        Destination(id: "Red Sea South", zh: "南红海", en: "Red Sea South",
            regionZH: "埃及", regionEN: "Egypt", lat: 24.0, lon: 35.5,
            months: m([(10, 12), (5, 7)]), tempC: 25...29,
            species: ["hammerhead", "reefshark"],
            noteZH: "Elphinstone 远洋白鳍鲨 10-12 月，Daedalus 锤头鲨夏季",
            noteEN: "Oceanic whitetips at Elphinstone Oct–Dec; Daedalus hammerheads summer",
            coldWater: false),
        Destination(id: "Maldives", zh: "马尔代夫", en: "Maldives",
            regionZH: "印度洋", regionEN: "Indian Ocean", lat: 3.2, lon: 73.2,
            months: m([(1, 4), (5, 11)]), tempC: 27...30,
            species: ["manta", "whaleshark", "reefshark"],
            noteZH: "1-4 月中环礁季；5-11 月 Hanifaru 湾蝠鲼旋涡（Baa 环礁）",
            noteEN: "Central atolls Jan–Apr; Hanifaru Bay manta cyclones May–Nov",
            coldWater: false),
        Destination(id: "Ningaloo", zh: "宁加洛礁", en: "Ningaloo Reef",
            regionZH: "西澳", regionEN: "Western Australia", lat: -22.7, lon: 113.68,
            months: m([(3, 7)]), tempC: 24...28,
            species: ["whaleshark", "humpback", "manta"],
            noteZH: "珊瑚产卵引来鲸鲨 3-7 月；8-10 月改看座头鲸",
            noteEN: "Whale sharks follow coral spawn Mar–Jul; humpbacks Aug–Oct",
            coldWater: false),

        // ===== 非洲 =====
        Destination(id: "Sardine Run", zh: "沙丁鱼大迁徙", en: "Sardine Run",
            regionZH: "南非", regionEN: "South Africa", lat: -31.6, lon: 29.55,
            months: m([(6, 7)]), tempC: 17...21,
            species: ["sardine", "reefshark", "humpback"],
            noteZH: "海豚+鲨鱼+塘鹅协同猎杀 bait ball，海洋版动物大迁徙",
            noteEN: "Dolphins, sharks and gannets blitzing bait balls — the ocean's great migration",
            coldWater: true),
        Destination(id: "Aliwal Shoal", zh: "阿利瓦尔浅滩", en: "Aliwal Shoal",
            regionZH: "南非", regionEN: "South Africa", lat: -30.25, lon: 30.82,
            months: m([(6, 11)]), tempC: 19...24,
            species: ["tigershark", "reefshark"],
            noteZH: "冬季沙虎鲨（raggies）聚集；虎鲨潜 2-6 月",
            noteEN: "Ragged-tooth aggregations in winter; tiger dives Feb–Jun",
            coldWater: true),
        Destination(id: "Cape Town", zh: "开普敦", en: "Cape Town",
            regionZH: "南非", regionEN: "South Africa", lat: -34.2, lon: 18.45,
            months: m([(6, 9)]), tempC: 8...16,
            species: ["kelp", "sealion", "reefshark"],
            noteZH: "《我的章鱼老师》的大西洋海藻林，七鳃鲨 + 海狗，干衣潜",
            noteEN: "My Octopus Teacher kelp forests; sevengills & fur seals; drysuit",
            coldWater: true),

        // ===== 冷水殿堂 =====
        Destination(id: "God's Pocket", zh: "God's Pocket", en: "God's Pocket",
            regionZH: "加拿大 BC", regionEN: "British Columbia", lat: 50.84, lon: -127.6,
            months: m([(12, 4), (5, 10)]), tempC: 7...10,
            species: ["gpo", "macro", "kelp"],
            noteZH: "Browning Wall 无脊椎糊墙天花板，冬季能见 20-30m",
            noteEN: "Browning Wall — invertebrate saturation; 20-30 m winter vis",
            coldWater: true),
        Destination(id: "Hornby Island", zh: "霍恩比岛", en: "Hornby Island",
            regionZH: "加拿大 BC", regionEN: "British Columbia", lat: 49.53, lon: -124.63,
            months: m([(12, 4)]), tempC: 7...9,
            species: ["sealion"],
            noteZH: "冬季与野生海狮群混潜，被扑咬蛙鞋是保留节目",
            noteEN: "Winter dives inside wild Steller sea lion mobs",
            coldWater: true),
        Destination(id: "Norway Orcas", zh: "挪威北部", en: "Northern Norway",
            regionZH: "挪威", regionEN: "Norway", lat: 69.8, lon: 20.7,
            months: m([(11, 1)]), tempC: 4...7,
            species: ["orca", "humpback", "wreck"],
            noteZH: "鲱鱼季与虎鲸/座头鲸同游（浮潜）+ 纳尔维克二战沉船",
            noteEN: "Orca & humpback herring blitz (snorkel) + Narvik WWII wrecks",
            coldWater: true),
        Destination(id: "Silfra", zh: "史费拉裂缝", en: "Silfra",
            regionZH: "冰岛", regionEN: "Iceland", lat: 64.26, lon: -21.12,
            months: m([(1, 12)]), tempC: 2...4,
            species: ["cave"],
            noteZH: "两大洲板块之间，能见度 100m+ 的冰川水",
            noteEN: "Between two continental plates; 100 m+ glacial visibility",
            coldWater: true),
        Destination(id: "Scapa Flow", zh: "斯卡帕湾", en: "Scapa Flow",
            regionZH: "苏格兰", regionEN: "Scotland", lat: 58.89, lon: -3.05,
            months: m([(4, 10)]), tempC: 8...14,
            species: ["wreck"],
            noteZH: "一战德国公海舰队整支自沉于此，Tech 沉船圣地",
            noteEN: "The scuttled WWI German High Seas Fleet; tech wreck mecca",
            coldWater: true),
        Destination(id: "Poor Knights", zh: "穷骑士群岛", en: "Poor Knights",
            regionZH: "新西兰", regionEN: "New Zealand", lat: -35.47, lon: 174.73,
            months: m([(1, 5)]), tempC: 16...22,
            species: ["reefshark", "kelp", "macro"],
            noteZH: "火山拱门 + 魟鱼群，Cousteau 十佳常客",
            noteEN: "Volcanic arches, stingray squadrons; a Cousteau top-10 regular",
            coldWater: true),
        Destination(id: "Fiordland", zh: "峡湾地区", en: "Fiordland",
            regionZH: "新西兰", regionEN: "New Zealand", lat: -45.42, lon: 167.05,
            months: m([(10, 4)]), tempC: 12...16,
            species: ["kelp", "macro"],
            noteZH: "茶色表层把黑珊瑚压到 10-20m 休闲深度，全球独此一家",
            noteEN: "Tannin layer brings black corals up to 10-20 m — nowhere else on Earth",
            coldWater: true),
        Destination(id: "Whyalla", zh: "怀阿拉", en: "Whyalla",
            regionZH: "南澳", regionEN: "South Australia", lat: -33.03, lon: 137.58,
            months: m([(5, 8)]), tempC: 12...15,
            species: ["cuttlefish"],
            noteZH: "数十万巨型乌贼冬季求偶变色，浅水岸潜即达",
            noteEN: "Hundreds of thousands of giant cuttlefish courting in the shallows",
            coldWater: true),
        Destination(id: "Rapid Bay", zh: "急流湾", en: "Rapid Bay",
            regionZH: "南澳", regionEN: "South Australia", lat: -35.52, lon: 138.18,
            months: m([(1, 12)]), tempC: 14...20,
            species: ["dragon", "macro"],
            noteZH: "码头桩下找叶海龙，海龙科爱好者必修",
            noteEN: "Leafy sea dragons under the jetty, year-round",
            coldWater: true),
        Destination(id: "Hokkaido", zh: "北海道知床", en: "Hokkaido (Shiretoko)",
            regionZH: "日本", regionEN: "Japan", lat: 44.07, lon: 145.12,
            months: m([(2, 3)]), tempC: -1...2,
            species: ["macro"],
            noteZH: "流冰下潜水找冰海天使 Clione，2 月限定",
            noteEN: "Drift-ice diving for sea angels (Clione); February only",
            coldWater: true),
        Destination(id: "Mikomoto", zh: "神子元岛", en: "Mikomoto",
            regionZH: "日本", regionEN: "Japan", lat: 34.57, lon: 138.94,
            months: m([(6, 10)]), tempC: 20...26,
            species: ["hammerhead"],
            noteZH: "离东京最近的锤头鲨群，流大，进阶潜点",
            noteEN: "Hammerhead schools closest to Tokyo; strong currents",
            coldWater: false),
    ]
}
